# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-25 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='content',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
